### ISSUE TITLE
Error while crawling at large size domains

### ISSUE THREAD

**Issue by waelahmed-dev** [MayankPandey01/BrokenLinkHijacker#6]
Sometimes, I get this error and I guess it happens when the target domain contains many links in it

```
ERROR While Crawling
maximum recursion depth exceeded while calling a Python object
```

**Comment by waelahmed-dev** [comment]
After adding this line:
`sys.setrecursionlimit(10000)`

I got this error:
```
ERROR While Crawling
Exceeded 30 redirects.
```

**Comment by MayankPandey01** [comment]
@waelahmed-dev you can change the value of **sys.setrecursionlimit()** on your Local System according to your use case.
